# Build commands

## Production build command
[build]
  command = "npm run build"
  functions = "./lib/functions"

## Non-production build command
[context.deploy-preview]
  command = "npm run staging"

[context.branch-deploy]
  command = "npm run staging"
  base = "."
  functions = "./lib/functions"

# Allow fonts to be used by other domains (disable CORS), also cache fonts
[[headers]]
  for = "/assets/fonts/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"

# Internal redirects

## Redirect default Netlify subdomain to primary domain

[[redirects]]
  from = "https://tempertemper.netlify.com/*"
  to = "https://tempertemper.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://tempertemper.netlify.app/*"
  to = "https://tempertemper.net/:splat"
  status = 301
  force = true
